// +build !ignore_autogenerated

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackOverDriveSecret) DeepCopyInto(out *StackOverDriveSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackOverDriveSecret.
func (in *StackOverDriveSecret) DeepCopy() *StackOverDriveSecret {
	if in == nil {
		return nil
	}
	out := new(StackOverDriveSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackOverDriveSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackOverDriveSecretList) DeepCopyInto(out *StackOverDriveSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StackOverDriveSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackOverDriveSecretList.
func (in *StackOverDriveSecretList) DeepCopy() *StackOverDriveSecretList {
	if in == nil {
		return nil
	}
	out := new(StackOverDriveSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackOverDriveSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackOverDriveSecretSpec) DeepCopyInto(out *StackOverDriveSecretSpec) {
	*out = *in
	if in.EncryptedData != nil {
		in, out := &in.EncryptedData, &out.EncryptedData
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackOverDriveSecretSpec.
func (in *StackOverDriveSecretSpec) DeepCopy() *StackOverDriveSecretSpec {
	if in == nil {
		return nil
	}
	out := new(StackOverDriveSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackOverDriveSecretStatus) DeepCopyInto(out *StackOverDriveSecretStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackOverDriveSecretStatus.
func (in *StackOverDriveSecretStatus) DeepCopy() *StackOverDriveSecretStatus {
	if in == nil {
		return nil
	}
	out := new(StackOverDriveSecretStatus)
	in.DeepCopyInto(out)
	return out
}
